name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
 
jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Inspect machine
        run: |
          ls -al
          whoami
          pwd
          node -v