name: E2E Tests

on: 
  workflow_dispatch:

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      # 1) Build hangman-api
      - name: Build hangman-api image
        working-directory: .start-code/hangman-api
        run: docker build -t hangman-api:latest .

      # 2) Build hangman-front
      - name: Build hangman-front image
        working-directory: .start-code/hangman-front
        run: docker build -t hangman-front:latest .

      # 3) Run the containers
      - name: Start hangman-api
        run: docker run -d --name hangman-api -p 3001:3000 hangman-api:latest

      - name: Start hangman-front
        run: docker run -d --name hangman-front -p 8080:8080 -e API_URL=http://localhost:3001 hangman-front:latest

      # (Opcional) Esperar a que inicien
      - name: Wait containers
        run: sleep 5

      # 4) Instalar y ejecutar los E2E
      - name: Install E2E dependencies
        working-directory: .start-code/hangman-e2e/e2e
        run: npm install

      - name: Run E2E
        working-directory: .start-code/hangman-e2e/e2e
        run: npx cypress run  # o "npm run test", según tu script
